compile: MemoryManagement.cpp VirtualMemory.cpp MainMemory.cpp PageTable.cpp LinkedList.cpp
	g++ -Wall MemoryManagement.cpp VirtualMemory.cpp MainMemory.cpp PageTable.cpp LinkedList.cpp -o VirtualMemoryManagementSystem
